"""empty message

Revision ID: 71eda2615fa0
Revises: 16bca2f6f745
Create Date: 2021-05-06 05:18:20.665105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71eda2615fa0'
down_revision = '16bca2f6f745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('artist', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
