"""empty message

Revision ID: 7b8a33cd9a43
Revises: 2df498086461
Create Date: 2021-05-09 10:43:11.898369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8a33cd9a43'
down_revision = '2df498086461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_song', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('playlist_song', 'playlist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playlist_song', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('playlist_song_playlist_id_fkey', 'playlist_song', type_='foreignkey')
    op.drop_constraint('playlist_song_song_id_fkey', 'playlist_song', type_='foreignkey')
    op.create_foreign_key(None, 'playlist_song', 'songs', ['song_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'playlist_song', 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')
    op.add_column('songs', sa.Column('album_image', sa.String(length=255), nullable=False))
    op.add_column('songs', sa.Column('album_name', sa.String(length=255), nullable=False))
    op.add_column('songs', sa.Column('artists', sa.String(length=255), nullable=False))
    op.add_column('songs', sa.Column('spotify_id', sa.String(length=255), nullable=False))
    op.drop_column('songs', 'artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('artist', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('songs', 'spotify_id')
    op.drop_column('songs', 'artists')
    op.drop_column('songs', 'album_name')
    op.drop_column('songs', 'album_image')
    op.drop_constraint(None, 'playlist_song', type_='foreignkey')
    op.drop_constraint(None, 'playlist_song', type_='foreignkey')
    op.create_foreign_key('playlist_song_song_id_fkey', 'playlist_song', 'songs', ['song_id'], ['id'])
    op.create_foreign_key('playlist_song_playlist_id_fkey', 'playlist_song', 'playlists', ['playlist_id'], ['id'])
    op.alter_column('playlist_song', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playlist_song', 'playlist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('playlist_song', 'id')
    # ### end Alembic commands ###
